name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
    - '**.sh'
    - '**/Dockerfile'
    - '.github/workflows/docker-image.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3.6.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v5.7.0
      with:
        images: |
          ghcr.io/tarboox45-cpu/tahou45-qu
          tarboox45-cpu/xhost-vps-egg
        tags: |
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v6.18.0
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
